
-- table to store raw match data from csv files and the API

CREATE TABLE raw_matches (
    time_added  TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL,
    match_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- sackmann dataset does not provide match ids, but each row is a new match
    tourney_id TEXT,
    tourney_name TEXT,
    surface TEXT,
    draw_size INTEGER,
    tourney_level TEXT,
    tourney_date   DATE,
    match_num INTEGER,
    winner_id INTEGER,
    winner_seed INTEGER,
    winner_entry TEXT,
    winner_name TEXT,
    winner_hand TEXT,
    winner_ht INTEGER,
    winner_ioc TEXT,
    winner_age REAL,
    loser_id INTEGER,
    loser_seed INTEGER,
    loser_entry TEXT,
    loser_name TEXT,
    loser_hand TEXT,
    loser_ht INTEGER,
    loser_ioc TEXT,
    loser_age REAL,
    score TEXT,
    best_of INTEGER,
    round TEXT,
    minutes INTEGER,
    w_ace INTEGER,
    w_df INTEGER,
    w_svpt INTEGER,
    w_1stIn INTEGER,
    w_1stWon INTEGER,
    w_2ndWon INTEGER,
    w_SvGms INTEGER,
    w_bpSaved INTEGER,
    w_bpFaced INTEGER,
    l_ace INTEGER,
    l_df INTEGER,
    l_svpt INTEGER,
    l_1stIn INTEGER,
    l_1stWon INTEGER,
    l_2ndWon INTEGER,
    l_SvGms INTEGER,
    l_bpSaved INTEGER,
    l_bpFaced INTEGER,
    winner_rank INTEGER,
    winner_rank_points INTEGER,
    loser_rank INTEGER,
    loser_rank_points INTEGER,
    rapidapi_match_id INTEGER UNIQUE,
    rapidapi_tournament_id INTEGER,
    rapidapi_winner_id INTEGER,
    rapidapi_loser_id INTEGER,
    -- sackmann only has tournament date, match_date is a timestamp of match start time
    match_date DATE
);

-- =======================================
-- Tables for match data processed from raw_matches
-- players, tournaments, matches, and match stats
-- =======================================

CREATE TABLE players (
    -- the sackmann dataset already establishes an id so we use that when it exists
    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name TEXT NOT NULL,
    nationality TEXT,
    hand TEXT
);

CREATE TABLE tournaments (
    tournament_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    surface TEXT NOT NULL,
    tournament_level TEXT NOT NULL
);

-- will have to decide whether each year of an event counts as a separate tournament or same

CREATE TABLE matches (
    match_id INTEGER PRIMARY KEY,
    tournament_id TEXT REFERENCES tournaments(tournament_id),
    match_date DATE NOT NULL,
    round TEXT NOT NULL,
    round_int INTEGER,
    winner_id INTEGER REFERENCES players(player_id),
    loser_id INTEGER REFERENCES players(player_id),
    score TEXT
);

CREATE TABLE match_stats (
    match_id INTEGER REFERENCES matches(match_id),
    player_id INTEGER REFERENCES players(player_id),
    opponent_id INTEGER REFERENCES players(player_id),
    won BOOLEAN NOT NULL,
    complete_stats BOOLEAN NOT NULL, -- whether ALL of the following fields are not NULL

    aces INTEGER,
    double_faults INTEGER,
    service_points INTEGER,
    first_serves_in INTEGER,
    first_serve_points_won INTEGER,
    second_serve_points_won INTEGER,
    service_games INTEGER,
    break_points_saved INTEGER,
    break_points_faced INTEGER,

    return_points INTEGER,
    first_serve_return_points INTEGER,
    first_serve_return_points_won INTEGER,
    second_serve_return_points_won INTEGER,
    return_games INTEGER,
    break_points_converted INTEGER,
    break_points_chances INTEGER,

    PRIMARY KEY (match_id, player_id)
);

-- table for holding translation of API player IDs to established player IDs

CREATE TABLE player_id_lookup (
    player_id INTEGER REFERENCES players(player_id),
    api_player_id INTEGER NOT NULL,
    api_name TEXT NOT NULL,
    match_type TEXT NOT NULL,
    confidence REAL,

    PRIMARY KEY (player_id, api_player_id)
);

-- ====================
-- Tables for more advanced stats/aggregations
-- ====================

CREATE TABLE player_surface_stats (
    last_updated TIMESTAMPTZ NOT NULL,

    player_id INTEGER REFERENCES players(player_id),
    surface TEXT, -- NULL for all surfaces
    season INTEGER, -- year, NULL for career

    matches_played INTEGER,
    won INTEGER,

    aces INTEGER,
    double_faults INTEGER,
    service_points INTEGER,
    first_serves_in INTEGER,
    first_serve_points_won INTEGER,
    second_serve_points_won INTEGER,
    second_serve_points INTEGER, -- service_points - first_serves_in
    service_games INTEGER,
    service_games_won INTEGER, -- (service_games - (break_points_faced - break_points_saved))
    break_points_saved INTEGER,
    break_points_faced INTEGER,

    return_points INTEGER,
    first_serve_return_points INTEGER,
    first_serve_return_points_won INTEGER,
    second_serve_return_points INTEGER, -- return_points - first_serve_return_points
    second_serve_return_points_won INTEGER,
    return_games INTEGER,
    break_points_converted INTEGER, -- every break point converted is a return game won
    break_points_chances INTEGER,

    primary key (player_id, surface, season)
);

CREATE TABLE head_to_head (
    player_id       INTEGER REFERENCES players(player_id),
    opponent_id     INTEGER REFERENCES players(player_id),
    surface         TEXT,
    wins            INTEGER NOT NULL,
    losses          INTEGER NOT NULL,
    matches_played  INTEGER NOT NULL,
    last_updated    TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (player_id, opponent_id, surface)
);

CREATE TABLE player_form (
  matches_total INTEGER NOT NULL,
  won INTEGER not null,
  player_id INTEGER REFERENCES players(player_id),
  surface TEXT not null,
  last_updated timestamptz not null,
  weighted_form real
);

CREATE TABLE elo_history (
    player_id       INTEGER REFERENCES players(player_id),
    match_id        INTEGER REFERENCES matches(match_id),
    surface         TEXT NOT NULL,      -- 'Hard', 'Clay', 'Grass', 'ALL'
    match_date      DATE NOT NULL,
    elo_before      REAL NOT NULL,
    elo_after       REAL NOT NULL,
    k_factor        REAL NOT NULL,      -- store what K was used, useful for auditing
    opponent_id     INTEGER REFERENCES players(player_id),
    opponent_elo    REAL NOT NULL,      -- opponent rating at time of match
    expected        REAL NOT NULL,      -- E(A) — useful for validation later
    won             BOOLEAN NOT NULL,
    PRIMARY KEY (player_id, match_id, surface)
);

CREATE TABLE averaged_surface_elo_history (
    player_id INTEGER NOT NULL REFERENCES players(player_id),
    match_id INTEGER NOT NULL REFERENCES matches(match_id),
    surface TEXT NOT NULL,
    match_date DATE NOT NULL,

    expected REAL NOT NULL,
    won BOOLEAN NOT NULL,
    averaged_surface_elo REAL NOT NULL,

    overall_surface TEXT NOT NULL DEFAULT 'ALL' CHECK (overall_surface = 'ALL'),

    -- surface-specific elo_history row (same player/match/surface)
    FOREIGN KEY (player_id, match_id, surface)
        REFERENCES elo_history(player_id, match_id, surface),

    -- overall elo_history row (same player/match, but surface='ALL')
    FOREIGN KEY (player_id, match_id, overall_surface)
        REFERENCES elo_history(player_id, match_id, surface),

    PRIMARY KEY (player_id, match_id, surface)
);

-- used to keep track of which dates filled from API
-- when backfilling older data (end of 2024 to now)

CREATE TABLE backfill_progress (
    backfill_date   DATE PRIMARY KEY,
    completed_at    TIMESTAMPTZ NOT NULL
);
