
-- table to store raw match data from csv files and the API

CREATE TABLE raw_matches (
    time_added  TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL,
    match_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- sackmann dataset does not provide match ids, but each row is a new match
    tourney_id TEXT,
    tourney_name TEXT,
    surface TEXT,
    draw_size INTEGER,
    tourney_level TEXT,
    tourney_date   DATE,
    match_num INTEGER,
    winner_id INTEGER,
    winner_seed INTEGER,
    winner_entry TEXT,
    winner_name TEXT,
    winner_hand TEXT,
    winner_ht INTEGER,
    winner_ioc TEXT,
    winner_age REAL,
    loser_id INTEGER,
    loser_seed INTEGER,
    loser_entry TEXT,
    loser_name TEXT,
    loser_hand TEXT,
    loser_ht INTEGER,
    loser_ioc TEXT,
    loser_age REAL,
    score TEXT,
    best_of INTEGER,
    round TEXT,
    minutes INTEGER,
    w_ace INTEGER,
    w_df INTEGER,
    w_svpt INTEGER,
    w_1stIn INTEGER,
    w_1stWon INTEGER,
    w_2ndWon INTEGER,
    w_SvGms INTEGER,
    w_bpSaved INTEGER,
    w_bpFaced INTEGER,
    l_ace INTEGER,
    l_df INTEGER,
    l_svpt INTEGER,
    l_1stIn INTEGER,
    l_1stWon INTEGER,
    l_2ndWon INTEGER,
    l_SvGms INTEGER,
    l_bpSaved INTEGER,
    l_bpFaced INTEGER,
    winner_rank INTEGER,
    winner_rank_points INTEGER,
    loser_rank INTEGER,
    loser_rank_points INTEGER,
    rapidapi_match_id INTEGER UNIQUE,
    rapidapi_tournament_id INTEGER,
    rapidapi_winner_id INTEGER,
    rapidapi_loser_id INTEGER,
    -- sackmann only has tournament date, match_date is a timestamp of match start time
    match_date DATE
);

-- =======================================
-- Tables for match data processed from raw_matches
-- players, tournaments, matches, and match stats
-- =======================================

CREATE TABLE players (
    -- the sackmann dataset already establishes an id so we use that when it exists
    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name TEXT NOT NULL,
    nationality TEXT,
    hand TEXT,
);

CREATE TABLE tournaments (
    tournament_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    surface TEXT NOT NULL,
    tournament_level TEXT NOT NULL
);

-- will have to decide whether each year of an event counts as a separate tournament or same

CREATE TABLE matches (
    match_id INTEGER PRIMARY KEY,
    tournament_id TEXT REFERENCES tournaments(tournament_id),
    match_date DATE NOT NULL,
    round TEXT NOT NULL,
    winner_id INTEGER REFERENCES players(player_id),
    loser_id INTEGER REFERENCES players(player_id),
    score TEXT
);

CREATE TABLE match_stats (
    match_id INTEGER REFERENCES matches(match_id),
    player_id INTEGER REFERENCES players(player_id),
    opponent_id INTEGER REFERENCES players(player_id),
    won BOOLEAN NOT NULL,
    complete_stats BOOLEAN NOT NULL, -- whether ALL of the following fields are not NULL

    aces INTEGER,
    double_faults INTEGER,
    service_points INTEGER,
    first_serves_in INTEGER,
    first_serve_points_won INTEGER,
    second_serve_points_won INTEGER,
    service_games INTEGER,
    break_points_saved INTEGER,
    break_points_faced INTEGER,

    return_points INTEGER,
    first_serve_return_points INTEGER,
    first_serve_return_points_won INTEGER,
    second_serve_return_points_won INTEGER,
    return_games INTEGER,
    break_points_converted INTEGER,
    break_points_chances INTEGER,

    PRIMARY KEY (match_id, player_id)
);

-- table for holding translation of API player IDs to established player IDs

CREATE TABLE player_id_lookup (
    player_id INTEGER REFERENCES players(player_id),
    api_player_id INTEGER NOT NULL,
    api_name TEXT NOT NULL,
    match_type TEXT NOT NULL,
    confidence REAL,

    PRIMARY KEY (player_id, api_player_id)
);