name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STR: "sqlite:///:memory:"
      API_KEY: "test"
      DATASET_PATH: "test"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - run: pip install -r requirements.txt
      - run: python -m pytest
      - run: python -m ruff check . 